# Generated by Django 5.0.6

from django.db import migrations

def create_early_bird_badge(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    badge_data = {
        'slug': 'early-bird',
        'name': 'Early Bird',
        'description': 'Watched an episode within 1 hour of release',
        'icon_url': '/static/badges/early-bird.png'
    }
    if not Badge.objects.filter(slug=badge_data['slug']).exists():
        Badge.objects.create(**badge_data)

def remove_early_bird_badge(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    Badge.objects.filter(slug='early-bird').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_seed_commentator'),
    ]

    operations = [
        migrations.RunPython(create_early_bird_badge, remove_early_bird_badge),
    ]
