# Generated by Django 5.1.6 on 2024-02-22 10:00

from django.db import migrations

def seed_social_butterfly(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    Badge.objects.get_or_create(
        slug='social-butterfly',
        defaults={
            'name': 'Social Butterfly',
            'description': 'Participated in 5 different chat rooms.',
            'icon_url': '/static/badges/social-butterfly.png'
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_seed_early_bird'),
    ]

    operations = [
        migrations.RunPython(seed_social_butterfly),
    ]
