# Generated by Django 5.1.6

from django.db import migrations

def create_collector_badge(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    badge_data = {
        'slug': 'collector',
        'name': 'Collector',
        'description': 'Subscribed to 10 different anime',
        'icon_url': '/static/badges/collector.png'
    }
    if not Badge.objects.filter(slug=badge_data['slug']).exists():
        Badge.objects.create(**badge_data)

def remove_collector_badge(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    Badge.objects.filter(slug='collector').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_seed_social_butterfly'),
    ]

    operations = [
        migrations.RunPython(create_collector_badge, remove_collector_badge),
    ]
