# Generated by Django 5.1.6

from django.db import migrations

def create_season_completist_badge(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    badge_data = {
        'slug': 'season-completist',
        'name': 'Season Completist',
        'description': 'Completed an entire season',
        'icon_url': '/static/badges/season-completist.png'
    }
    if not Badge.objects.filter(slug=badge_data['slug']).exists():
        Badge.objects.create(**badge_data)

def remove_season_completist_badge(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    Badge.objects.filter(slug='season-completist').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_seed_collector_badge'),
    ]

    operations = [
        migrations.RunPython(create_season_completist_badge, remove_season_completist_badge),
    ]
