# Generated by Django 5.1.6 on 2026-01-21 04:05

from django.db import migrations

def create_genre_explorer_badge(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    Badge.objects.get_or_create(
        slug='genre-explorer',
        defaults={
            'name': 'Genre Explorer',
            'description': 'Watched anime from 5 different genres.',
            'icon_url': 'https://img.icons8.com/color/96/diversity.png',  # Placeholder icon
        }
    )

def remove_genre_explorer_badge(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    Badge.objects.filter(slug='genre-explorer').delete()

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_seed_weekend_warrior"),
    ]

    operations = [
        migrations.RunPython(create_genre_explorer_badge, remove_genre_explorer_badge),
    ]
