# Generated by Django 4.0.2 on 2024-03-05 12:00

from django.db import migrations

def seed_critic_badge(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    Badge.objects.get_or_create(
        slug='critic',
        defaults={
            'name': 'Critic',
            'description': 'Wrote your first review.',
            'icon_url': '/static/badges/critic.png',
            # 'points': 10  <-- Removed invalid field
        }
    )

def remove_critic_badge(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    Badge.objects.filter(slug='critic').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('users', '0016_auto_20260121_0929'),
    ]

    operations = [
        migrations.RunPython(seed_critic_badge, remove_critic_badge),
    ]
