# Generated by Django 5.1.6 on 2026-01-22 17:21

from django.db import migrations

def seed_genre_savant_badge(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    Badge.objects.get_or_create(
        slug='genre-savant',
        defaults={
            'name': 'Genre Savant',
            'description': 'Watched 50 episodes of a single genre.',
            'icon_url': '/static/badges/genre_savant.png'
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_seed_content_creator_badge"),
    ]

    operations = [
        migrations.RunPython(seed_genre_savant_badge),
    ]
