# Generated by Django 5.1.6 on 2026-01-22 20:27

from django.db import migrations

def seed_movie_buff_badge(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    Badge.objects.create(
        slug='movie-buff',
        name='Movie Buff',
        description='Watched 5 different anime movies.',
        icon_url='https://example.com/badges/movie-buff.png'  # Placeholder URL
    )

def remove_movie_buff_badge(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    Badge.objects.filter(slug='movie-buff').delete()

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_seed_pilot_connoisseur_badge"),
    ]

    operations = [
        migrations.RunPython(seed_movie_buff_badge, remove_movie_buff_badge),
    ]
