# Generated by Django 5.1.6 on 2026-01-22 21:12

from django.db import migrations

def seed_trendsetter_badge(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    Badge.objects.get_or_create(
        slug='trendsetter',
        defaults={
            'name': 'Trendsetter',
            'description': 'Hosted a Watch Party with 5 concurrent viewers.',
            # Badge model has icon_url, but we don't have a URL handy.
            # Leaving it blank or using a placeholder if needed.
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_seed_movie_buff_badge'),
    ]

    operations = [
        migrations.RunPython(seed_trendsetter_badge),
    ]
