# Generated by Django 5.1.6 on 2026-01-23 00:00

from django.db import migrations

def seed_super_fan_badge(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    Badge.objects.get_or_create(
        slug='super-fan',
        defaults={
            'name': 'Super Fan',
            'description': 'Completed all episodes of an anime series.',
            'icon_url': '/static/badges/super-fan.png'
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20260122_2112'),
    ]

    operations = [
        migrations.RunPython(seed_super_fan_badge),
    ]
