# Generated by Django 5.1.6 on 2026-01-23 00:00

from django.db import migrations

def seed_badges(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    Badge.objects.get_or_create(
        slug='review-guru',
        defaults={
            'name': 'Review Guru',
            'description': 'Wrote 20 reviews.',
            'icon_url': '/static/badges/review-guru.png'
        }
    )
    Badge.objects.get_or_create(
        slug='star-power',
        defaults={
            'name': 'Star Power',
            'description': 'Rated 5 anime with a perfect 10/10 score.',
            'icon_url': '/static/badges/star-power.png'
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_seed_super_fan_badge'),
    ]

    operations = [
        migrations.RunPython(seed_badges),
    ]
