# Generated by Django 5.1.6 on 2026-01-23 00:00

from django.db import migrations

def seed_otaku_badge(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    Badge.objects.get_or_create(
        slug='otaku',
        defaults={
            'name': 'Otaku',
            'description': 'Completed 5 different anime series.',
            'icon_url': '/static/badges/otaku.png'
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_seed_review_guru_and_star_power'),
    ]

    operations = [
        migrations.RunPython(seed_otaku_badge),
    ]
