# Generated by Django 5.1.6 on 2026-01-23 00:00

from django.db import migrations

def seed_century_club_badge(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    Badge.objects.get_or_create(
        slug='century-club',
        defaults={
            'name': 'Century Club',
            'description': "Watched 100 episodes. That's dedication!",
            'icon_url': '/static/badges/century_club.png'
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_seed_otaku_badge'),
    ]

    operations = [
        migrations.RunPython(seed_century_club_badge),
    ]
