# Generated by Django 5.1.6 on 2026-01-23 18:41

from django.db import migrations

def seed_badges(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')

    # Marathon Runner
    Badge.objects.get_or_create(
        slug='marathon-runner',
        defaults={
            'name': 'Marathon Runner',
            'description': 'Watched 12+ episodes in the last 24 hours.'
        }
    )

    # Millennium Club
    Badge.objects.get_or_create(
        slug='millennium-club',
        defaults={
            'name': 'Millennium Club',
            'description': 'Watched 1000 distinct episodes.'
        }
    )

def remove_badges(apps, schema_editor):
    Badge = apps.get_model('users', 'Badge')
    Badge.objects.filter(slug__in=['marathon-runner', 'millennium-club']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_seed_daily_viewer_badge"),
    ]

    operations = [
        migrations.RunPython(seed_badges, remove_badges),
    ]
