# Generated by Django 5.1.6 on 2026-03-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_seed_marathon_runner_and_millennium_club"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="users_notif_user_id_1be17e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "-created_at"], name="users_notif_user_id_c37f16_idx"
            ),
        ),
    ]
