# Generated by Django 5.1.6 on 2026-03-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_subscription_content_sub_user_id_930f7c_idx"),
        ("users", "0036_notification_users_notif_user_id_1be17e_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="watchlog",
            index=models.Index(
                fields=["user", "watched_at"], name="users_watch_user_id_e6f5ff_idx"
            ),
        ),
    ]
