# Generated by Django 6.0.4 on 2026-04-19 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_alter_subtitle_file"),
        ("users", "0036_notification_users_notif_user_id_1be17e_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500, verbose_name="bio"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits, and _/- only.",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_username",
                        message="Enter a valid username. This value may contain only letters, numbers, and _/- characters.",
                        regex="^[\\w-]+$",
                    )
                ],
                verbose_name="username",
            ),
        ),
        migrations.AddIndex(
            model_name="watchlog",
            index=models.Index(
                fields=["user", "watched_at"], name="users_watch_user_id_e6f5ff_idx"
            ),
        ),
    ]
