# Generated by Django 5.1.6 on 2026-03-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_notification_users_notif_user_id_1be17e_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Biography"),
        ),
    ]
