# Generated by Django 5.1.6 on 2026-03-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_watchlog_users_watch_user_id_e6f5ff_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="Bio"),
        ),
    ]
