# Generated by Django 5.1.6 on 2026-03-22 12:24

import users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_watchlog_users_watch_user_id_e6f5ff_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="Biography"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and _/- only.",
                max_length=150,
                unique=True,
                    validators=[django.core.validators.RegexValidator(code='invalid_username', message='Enter a valid username. This value may contain only letters, numbers, and _/- characters.', regex='^[\\w-]+$')],
                verbose_name="username",
            ),
        ),
    ]
