# Generated by Django 5.1.6 on 2026-04-19 20:51

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500, verbose_name="bio"),
        ),
    ]
