# Generated by Django 5.1.6 on 2026-03-20 10:12

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0040_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="icon_url",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[core.validators.validate_image_mimetype],
            ),
        ),
    ]
