# Generated by Django 6.0.1 on 2026-01-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="AniScrap", max_length=100)),
                (
                    "contact_email",
                    models.EmailField(default="info@bariskeser.com", max_length=254),
                ),
                (
                    "abuse_email",
                    models.EmailField(default="abuse@bariskeser.com", max_length=254),
                ),
                (
                    "dmca_email",
                    models.EmailField(default="dmca@bariskeser.com", max_length=254),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
            ],
        ),
    ]
