# Generated by Django 6.0.1 on 2026-01-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="e.g. 'header', 'sidebar', 'footer'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("code", models.TextField(help_text="HTML/JS code for the ad")),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="abuse_email",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="dmca_email",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="site_name",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="deepl_api_keys",
            field=models.TextField(
                default="", help_text="Comma separated DeepL API keys"
            ),
        ),
    ]
