# Generated by Django 5.1.6 on 2026-03-13 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_subscription_content_sub_user_id_930f7c_idx"),
        ("watchparty", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["is_active"], name="watchparty__is_acti_09cc59_idx"
            ),
        ),
    ]
