# Generated by Django 5.1.6 on 2026-03-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchparty", "0002_room_watchparty__is_acti_09cc59_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="Optional password for private rooms",
                max_length=128,
                null=True,
            ),
        ),
    ]
