# Generated by Django 6.0.1 on 2026-01-19 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FansubGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("title", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Subtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang", models.CharField(default="tr", max_length=10)),
                ("file", models.FileField(upload_to="subtitles/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("480p", "480p"),
                            ("720p", "720p"),
                            ("1080p", "1080p"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "hls_path",
                    models.CharField(help_text="Path to .m3u8 file", max_length=500),
                ),
                (
                    "encryption_key",
                    models.CharField(help_text="AES-128 Key", max_length=255),
                ),
                (
                    "is_hardcoded",
                    models.BooleanField(
                        default=False, help_text="Disables Subtitle uploads if True"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="videokey",
            name="episode",
        ),
        migrations.AlterModelOptions(
            name="episode",
            options={},
        ),
        migrations.RenameField(
            model_name="anime",
            old_name="description",
            new_name="synopsis",
        ),
        migrations.AlterUniqueTogether(
            name="episode",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="anime",
            name="meta_description",
        ),
        migrations.RemoveField(
            model_name="anime",
            name="meta_keywords",
        ),
        migrations.RemoveField(
            model_name="anime",
            name="meta_title",
        ),
        migrations.RemoveField(
            model_name="anime",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="anime",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="episode",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="anime",
            name="cover_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="episode",
            name="number",
            field=models.PositiveIntegerField(),
        ),
    ]
