# Generated by Django 6.0.1 on 2026-01-19 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_fansubgroup_season_subtitle_videofile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fansubgroup",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fansub_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="anime",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seasons",
                to="content.anime",
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="season",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="content.season",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subtitle",
            name="episode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtitles",
                to="content.episode",
            ),
        ),
        migrations.AddField(
            model_name="subtitle",
            name="fansub_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtitles",
                to="content.fansubgroup",
            ),
        ),
        migrations.AddField(
            model_name="videofile",
            name="episode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_files",
                to="content.episode",
            ),
        ),
        migrations.AddField(
            model_name="videofile",
            name="fansub_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videos",
                to="content.fansubgroup",
            ),
        ),
        migrations.AddField(
            model_name="videofile",
            name="uploader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_videos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="VideoKey",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="anime",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="hls_playlist",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="is_processed",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="source_file",
        ),
    ]
