# Generated by Django 6.0.1 on 2026-01-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_fansubgroup_owner_season_anime_episode_season_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videofile",
            name="file_size_bytes",
            field=models.BigIntegerField(
                default=0, help_text="Total size of HLS assets in bytes"
            ),
        ),
    ]
