# Generated by Django 5.1.6 on 2026-01-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="anime",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="animes", to="content.genre"
            ),
        ),
    ]
