# Generated by Django 5.1.6 on 2026-01-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_watchparty"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="type",
            field=models.CharField(
                choices=[
                    ("TV", "TV Series"),
                    ("Movie", "Movie"),
                    ("OVA", "OVA"),
                    ("ONA", "ONA"),
                    ("Special", "Special"),
                ],
                default="TV",
                max_length=20,
            ),
        ),
    ]
