# Generated by Django 5.1.6 on 2026-01-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_anime_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchparty",
            name="max_participants",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
