# Generated by Django 5.1.6 on 2026-01-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_jikan_api_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchParty',
        ),
    ]
