# Generated by Django 5.1.6 on 2026-02-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_delete_watchparty"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="anime",
            index=models.Index(
                fields=["popularity"], name="content_ani_popular_c321d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anime",
            index=models.Index(fields=["score"], name="content_ani_score_f94e2e_idx"),
        ),
        migrations.AddIndex(
            model_name="anime",
            index=models.Index(fields=["status"], name="content_ani_status_6727a1_idx"),
        ),
        migrations.AddIndex(
            model_name="anime",
            index=models.Index(
                fields=["created_at"], name="content_ani_created_d5b20a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["created_at"], name="content_epi_created_a274e2_idx"
            ),
        ),
    ]
