# Generated by Django 5.1.6 on 2026-03-13 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_anime_content_ani_popular_c321d9_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["user", "anime"], name="content_sub_user_id_930f7c_idx"
            ),
        ),
    ]
