# Generated by Django 5.1.6 on 2026-03-22 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_subscription_content_sub_user_id_930f7c_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtitle",
            name="file",
            field=models.FileField(
                upload_to="subtitles/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["srt", "vtt", "ass"]
                    )
                ],
            ),
        ),
    ]
