# Generated by Django 5.1.6 on 2026-03-17 03:17

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_subscription_content_sub_user_id_930f7c_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalsource",
            name="embed_url",
            field=models.CharField(
                help_text="Embed/iframe URL",
                max_length=500,
                validators=[
                    django.core.validators.RegexValidator(
                        message="URL must start with magnet: or https://",
                        regex="^(https://|magnet:\\?)",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="subtitle",
            name="file",
            field=models.FileField(
                upload_to="subtitles/",
                validators=[core.validators.validate_mime_type],
            ),
        ),
    ]
