# Generated by Django 5.1.6 on 2026-03-20 10:12

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_alter_externalsource_embed_url_alter_subtitle_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="banner_image",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[core.validators.validate_image_mimetype],
                verbose_name="Banner Image",
            ),
        ),
        migrations.AlterField(
            model_name="anime",
            name="cover_image",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[core.validators.validate_image_mimetype],
            ),
        ),
        migrations.AlterField(
            model_name="animecharacter",
            name="voice_actor_image",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[core.validators.validate_image_mimetype],
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="image_url",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[core.validators.validate_image_mimetype],
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="thumbnail",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[core.validators.validate_image_mimetype],
            ),
        ),
    ]
