# Generated by Django 6.0.5 on 2026-05-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_alter_externalsource_embed_url_alter_subtitle_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalsource",
            name="embed_url",
            field=models.URLField(help_text="Embed/iframe URL"),
        ),
    ]
