# Generated by Django 5.1.6 on 2026-03-22 12:26

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_alter_externalsource_embed_url_alter_subtitle_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="covers/",
                validators=[core.validators.validate_image_mimetype],
                verbose_name="Banner Image",
            ),
        ),
        migrations.AlterField(
            model_name="anime",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="covers/",
                validators=[core.validators.validate_image_mimetype],
            ),
        ),
    ]
