# Generated by Django 6.0.5 on 2026-05-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_alter_subtitle_file"),
        ("content", "0016_alter_externalsource_embed_url"),
    ]

    operations = []
